//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfatalsFirestoneTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfatalsFirestoneTools.Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability.
        /// </summary>
        public static string Ability {
            get {
                return ResourceManager.GetString("Ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aegis.
        /// </summary>
        public static string AegisLabel {
            get {
                return ResourceManager.GetString("AegisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amun.
        /// </summary>
        public static string AmunLabel {
            get {
                return ResourceManager.GetString("AmunLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angel.
        /// </summary>
        public static string Angel {
            get {
                return ResourceManager.GetString("Angel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzo.
        /// </summary>
        public static string AnzoLabel {
            get {
                return ResourceManager.GetString("AnzoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena.
        /// </summary>
        public static string Arena {
            get {
                return ResourceManager.GetString("Arena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena Power.
        /// </summary>
        public static string ArenaPower {
            get {
                return ResourceManager.GetString("ArenaPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena Stats.
        /// </summary>
        public static string ArenaStats {
            get {
                return ResourceManager.GetString("ArenaStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor BP (High→Low).
        /// </summary>
        public static string ArmorBPHighToLow {
            get {
                return ResourceManager.GetString("ArmorBPHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor BP (Low→High).
        /// </summary>
        public static string ArmorBPLowToHigh {
            get {
                return ResourceManager.GetString("ArmorBPLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor (High→Low).
        /// </summary>
        public static string ArmorHighToLow {
            get {
                return ResourceManager.GetString("ArmorHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor (Low→High).
        /// </summary>
        public static string ArmorLowToHigh {
            get {
                return ResourceManager.GetString("ArmorLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Percentage.
        /// </summary>
        public static string ArmorPercentage {
            get {
                return ResourceManager.GetString("ArmorPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifact Configuration.
        /// </summary>
        public static string ArtifactConfiguration {
            get {
                return ResourceManager.GetString("ArtifactConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure artifacts by stat type and percentage tier..
        /// </summary>
        public static string ArtifactConfigurationDescription {
            get {
                return ResourceManager.GetString("ArtifactConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artifacts.
        /// </summary>
        public static string Artifacts {
            get {
                return ResourceManager.GetString("Artifacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arvie.
        /// </summary>
        public static string ArvieLabel {
            get {
                return ResourceManager.GetString("ArvieLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asmondai.
        /// </summary>
        public static string AsmondaiLabel {
            get {
                return ResourceManager.GetString("AsmondaiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astrid.
        /// </summary>
        public static string AstridLabel {
            get {
                return ResourceManager.GetString("AstridLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Speed.
        /// </summary>
        public static string AttackSpeed {
            get {
                return ResourceManager.GetString("AttackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Style.
        /// </summary>
        public static string AttackStyle {
            get {
                return ResourceManager.GetString("AttackStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Armor.
        /// </summary>
        public static string BaseArmor {
            get {
                return ResourceManager.GetString("BaseArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Damage.
        /// </summary>
        public static string BaseDamage {
            get {
                return ResourceManager.GetString("BaseDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Health.
        /// </summary>
        public static string BaseHealth {
            get {
                return ResourceManager.GetString("BaseHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Stats.
        /// </summary>
        public static string BaseStats {
            get {
                return ResourceManager.GetString("BaseStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Power.
        /// </summary>
        public static string BattlePower {
            get {
                return ResourceManager.GetString("BattlePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Stats.
        /// </summary>
        public static string BattleStats {
            get {
                return ResourceManager.GetString("BattleStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belien.
        /// </summary>
        public static string BelienLabel {
            get {
                return ResourceManager.GetString("BelienLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benedictus.
        /// </summary>
        public static string BenedictusLabel {
            get {
                return ResourceManager.GetString("BenedictusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blaze.
        /// </summary>
        public static string BlazeLabel {
            get {
                return ResourceManager.GetString("BlazeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint Levels.
        /// </summary>
        public static string BlueprintLevels {
            get {
                return ResourceManager.GetString("BlueprintLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boris.
        /// </summary>
        public static string BorisLabel {
            get {
                return ResourceManager.GetString("BorisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Armor.
        /// </summary>
        public static string BP_Armor {
            get {
                return ResourceManager.GetString("BP_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Damage.
        /// </summary>
        public static string BP_Damage {
            get {
                return ResourceManager.GetString("BP_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BP Health.
        /// </summary>
        public static string BP_Health {
            get {
                return ResourceManager.GetString("BP_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        public static string Bronze {
            get {
                return ResourceManager.GetString("Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Edit.
        /// </summary>
        public static string BulkEdit {
            get {
                return ResourceManager.GetString("BulkEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burt.
        /// </summary>
        public static string BurtLabel {
            get {
                return ResourceManager.GetString("BurtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Strange Dust Needed.
        /// </summary>
        public static string CalculateStrangeDustNeeded {
            get {
                return ResourceManager.GetString("CalculateStrangeDustNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Progression.
        /// </summary>
        public static string CampaignProgression {
            get {
                return ResourceManager.GetString("CampaignProgression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celestial.
        /// </summary>
        public static string Celestial {
            get {
                return ResourceManager.GetString("Celestial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos Rift Rank.
        /// </summary>
        public static string ChaosRiftRank {
            get {
                return ResourceManager.GetString("ChaosRiftRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cirilo.
        /// </summary>
        public static string CiriloLabel {
            get {
                return ResourceManager.GetString("CiriloLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        public static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudfist.
        /// </summary>
        public static string CloudfistLabel {
            get {
                return ResourceManager.GetString("CloudfistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured First.
        /// </summary>
        public static string ConfiguredFirst {
            get {
                return ResourceManager.GetString("ConfiguredFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew Bonus Percentages.
        /// </summary>
        public static string CrewBonusPercentages {
            get {
                return ResourceManager.GetString("CrewBonusPercentages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit Chance.
        /// </summary>
        public static string CritChance {
            get {
                return ResourceManager.GetString("CritChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crit Damage.
        /// </summary>
        public static string CritDamage {
            get {
                return ResourceManager.GetString("CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown.
        /// </summary>
        public static string Crown {
            get {
                return ResourceManager.GetString("Crown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowns.
        /// </summary>
        public static string Crowns {
            get {
                return ResourceManager.GetString("Crowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curator.
        /// </summary>
        public static string CuratorLabel {
            get {
                return ResourceManager.GetString("CuratorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Exp.
        /// </summary>
        public static string CurrentExp {
            get {
                return ResourceManager.GetString("CurrentExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Position.
        /// </summary>
        public static string CurrentPosition {
            get {
                return ResourceManager.GetString("CurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage BP (High→Low).
        /// </summary>
        public static string DamageBPHighToLow {
            get {
                return ResourceManager.GetString("DamageBPHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage BP (Low→High).
        /// </summary>
        public static string DamageBPLowToHigh {
            get {
                return ResourceManager.GetString("DamageBPLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage (High→Low).
        /// </summary>
        public static string DamageHighToLow {
            get {
                return ResourceManager.GetString("DamageHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage (Low→High).
        /// </summary>
        public static string DamageLowToHigh {
            get {
                return ResourceManager.GetString("DamageLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Percentage.
        /// </summary>
        public static string DamagePercentage {
            get {
                return ResourceManager.GetString("DamagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danysa.
        /// </summary>
        public static string DanysaLabel {
            get {
                return ResourceManager.GetString("DanysaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        public static string Diamond {
            get {
                return ResourceManager.GetString("Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throws a fireball that deals 150% of its damage..
        /// </summary>
        public static string dmg_1x_150_Description {
            get {
                return ResourceManager.GetString("dmg_1x_150_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates an energy beam that deals 160% of its damage..
        /// </summary>
        public static string dmg_1x_160_Description {
            get {
                return ResourceManager.GetString("dmg_1x_160_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches a rocket that deals 200% of its damage..
        /// </summary>
        public static string dmg_1x_200_Description {
            get {
                return ResourceManager.GetString("dmg_1x_200_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack the last 2 war machines in the enemy formation with an energy beam that deals 130% of its damage..
        /// </summary>
        public static string dmg_2x_130_Description {
            get {
                return ResourceManager.GetString("dmg_2x_130_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fires cannonballs at 2 random war machines that deal 60% of its damage..
        /// </summary>
        public static string dmg_2x_60_Description {
            get {
                return ResourceManager.GetString("dmg_2x_60_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrifies 3 random war machines for 120% of its damage..
        /// </summary>
        public static string dmg_3x_120_Description {
            get {
                return ResourceManager.GetString("dmg_3x_120_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches rockets that deal 60% of its damage to all enemy war machines..
        /// </summary>
        public static string dmg_all_60_Description {
            get {
                return ResourceManager.GetString("dmg_all_60_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slams the ground and causes an earthquake that deals 80% of its damage to all enemy war machines..
        /// </summary>
        public static string dmg_all_80_Description {
            get {
                return ResourceManager.GetString("dmg_all_80_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodge.
        /// </summary>
        public static string Dodge {
            get {
                return ResourceManager.GetString("Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS / Healer.
        /// </summary>
        public static string DPSHealer {
            get {
                return ResourceManager.GetString("DPSHealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        public static string Druid {
            get {
                return ResourceManager.GetString("Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthshatterer.
        /// </summary>
        public static string EarthshattererLabel {
            get {
                return ResourceManager.GetString("EarthshattererLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald.
        /// </summary>
        public static string Emerald {
            get {
                return ResourceManager.GetString("Emerald", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        public static string Engineer {
            get {
                return ResourceManager.GetString("Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer Level.
        /// </summary>
        public static string EngineerLevel {
            get {
                return ResourceManager.GetString("EngineerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic.
        /// </summary>
        public static string Epic {
            get {
                return ResourceManager.GetString("Epic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolution &amp; Rank.
        /// </summary>
        public static string EvolutionAndRank {
            get {
                return ResourceManager.GetString("EvolutionAndRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolution Path.
        /// </summary>
        public static string EvolutionPath {
            get {
                return ResourceManager.GetString("EvolutionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolution(s).
        /// </summary>
        public static string Evolutions {
            get {
                return ResourceManager.GetString("Evolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXP Needed.
        /// </summary>
        public static string EXPNeeded {
            get {
                return ResourceManager.GetString("EXPNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fini.
        /// </summary>
        public static string FiniLabel {
            get {
                return ResourceManager.GetString("FiniLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firecracker.
        /// </summary>
        public static string FirecrackerLabel {
            get {
                return ResourceManager.GetString("FirecrackerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Evolutions.
        /// </summary>
        public static string ForEvolutions {
            get {
                return ResourceManager.GetString("ForEvolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Experience.
        /// </summary>
        public static string ForExperience {
            get {
                return ResourceManager.GetString("ForExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formation.
        /// </summary>
        public static string Formation {
            get {
                return ResourceManager.GetString("Formation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortress.
        /// </summary>
        public static string FortressLabel {
            get {
                return ResourceManager.GetString("FortressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Bonuses.
        /// </summary>
        public static string GlobalBonuses {
            get {
                return ResourceManager.GetString("GlobalBonuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God.
        /// </summary>
        public static string God {
            get {
                return ResourceManager.GetString("God", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goliath.
        /// </summary>
        public static string GoliathLabel {
            get {
                return ResourceManager.GetString("GoliathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvester.
        /// </summary>
        public static string HarvesterLabel {
            get {
                return ResourceManager.GetString("HarvesterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals all your war machines for 150% of its damage..
        /// </summary>
        public static string heal_all_150_Description {
            get {
                return ResourceManager.GetString("heal_all_150_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals the ally war machine with the lowest percentage of health for 300% of its damage..
        /// </summary>
        public static string heal_lowest_1x_300_Description {
            get {
                return ResourceManager.GetString("heal_lowest_1x_300_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals 2 random ally war machines for 350% of its damage..
        /// </summary>
        public static string heal_random_2x_350_Description {
            get {
                return ResourceManager.GetString("heal_random_2x_350_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores 10% of your maximum health..
        /// </summary>
        public static string heal_self_hp_10_Description {
            get {
                return ResourceManager.GetString("heal_self_hp_10_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healer.
        /// </summary>
        public static string Healer {
            get {
                return ResourceManager.GetString("Healer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health BP (High→Low).
        /// </summary>
        public static string HealthBPHighToLow {
            get {
                return ResourceManager.GetString("HealthBPHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health BP (Low→High).
        /// </summary>
        public static string HealthBPLowToHigh {
            get {
                return ResourceManager.GetString("HealthBPLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health (High→Low).
        /// </summary>
        public static string HealthHighToLow {
            get {
                return ResourceManager.GetString("HealthHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health (Low→High).
        /// </summary>
        public static string HealthLowToHigh {
            get {
                return ResourceManager.GetString("HealthLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Percentage.
        /// </summary>
        public static string HealthPercentage {
            get {
                return ResourceManager.GetString("HealthPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero.
        /// </summary>
        public static string Hero {
            get {
                return ResourceManager.GetString("Hero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroes.
        /// </summary>
        public static string Heroes {
            get {
                return ResourceManager.GetString("Heroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero List.
        /// </summary>
        public static string HeroList {
            get {
                return ResourceManager.GetString("HeroList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero Scoring Weights.
        /// </summary>
        public static string HeroScoringWeights {
            get {
                return ResourceManager.GetString("HeroScoringWeights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how heroes are prioritized per role. Changes apply on the next optimization..
        /// </summary>
        public static string HeroScoringWeightsDescription {
            get {
                return ResourceManager.GetString("HeroScoringWeightsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero Weights.
        /// </summary>
        public static string HeroWeights {
            get {
                return ResourceManager.GetString("HeroWeights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Clear.
        /// </summary>
        public static string HighestClear {
            get {
                return ResourceManager.GetString("HighestClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hongyu.
        /// </summary>
        public static string HongyuLabel {
            get {
                return ResourceManager.GetString("HongyuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        public static string Hunter {
            get {
                return ResourceManager.GetString("Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        public static string HunterLabel {
            get {
                return ResourceManager.GetString("HunterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ina.
        /// </summary>
        public static string InaLabel {
            get {
                return ResourceManager.GetString("InaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insane.
        /// </summary>
        public static string Insane {
            get {
                return ResourceManager.GetString("Insane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string Inscription {
            get {
                return ResourceManager.GetString("Inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription Card Level.
        /// </summary>
        public static string InscriptionCardLevel {
            get {
                return ResourceManager.GetString("InscriptionCardLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON.
        /// </summary>
        public static string InvalidJSON {
            get {
                return ResourceManager.GetString("InvalidJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid save data..
        /// </summary>
        public static string InvalidSaveData {
            get {
                return ResourceManager.GetString("InvalidSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iseris.
        /// </summary>
        public static string IserisLabel {
            get {
                return ResourceManager.GetString("IserisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jess.
        /// </summary>
        public static string JessLabel {
            get {
                return ResourceManager.GetString("JessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joe.
        /// </summary>
        public static string JoeLabel {
            get {
                return ResourceManager.GetString("JoeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judgement.
        /// </summary>
        public static string JudgementLabel {
            get {
                return ResourceManager.GetString("JudgementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kramatak.
        /// </summary>
        public static string KramatakLabel {
            get {
                return ResourceManager.GetString("KramatakLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layla.
        /// </summary>
        public static string LaylaLabel {
            get {
                return ResourceManager.GetString("LaylaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledra.
        /// </summary>
        public static string LedraLabel {
            get {
                return ResourceManager.GetString("LedraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        public static string Legendary {
            get {
                return ResourceManager.GetString("Legendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leo.
        /// </summary>
        public static string LeoLabel {
            get {
                return ResourceManager.GetString("LeoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level (High→Low).
        /// </summary>
        public static string LevelHighToLow {
            get {
                return ResourceManager.GetString("LevelHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level (Low→High).
        /// </summary>
        public static string LevelLowToHigh {
            get {
                return ResourceManager.GetString("LevelLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level must be 1-9.
        /// </summary>
        public static string LevelMustBeOneToNine {
            get {
                return ResourceManager.GetString("LevelMustBeOneToNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv..
        /// </summary>
        public static string LevelShort {
            get {
                return ResourceManager.GetString("LevelShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luana.
        /// </summary>
        public static string LuanaLabel {
            get {
                return ResourceManager.GetString("LuanaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine List.
        /// </summary>
        public static string MachineList {
            get {
                return ResourceManager.GetString("MachineList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines.
        /// </summary>
        public static string Machines {
            get {
                return ResourceManager.GetString("Machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage.
        /// </summary>
        public static string Mage {
            get {
                return ResourceManager.GetString("Mage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana.
        /// </summary>
        public static string Mana {
            get {
                return ResourceManager.GetString("Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Profiles.
        /// </summary>
        public static string ManageProfiles {
            get {
                return ResourceManager.GetString("ManageProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles let you manage multiple accounts or builds independently..
        /// </summary>
        public static string ManageProfilesDescription {
            get {
                return ResourceManager.GetString("ManageProfilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        public static string Melee {
            get {
                return ResourceManager.GetString("Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercenary.
        /// </summary>
        public static string Mercenary {
            get {
                return ResourceManager.GetString("Mercenary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrated save from old format..
        /// </summary>
        public static string MigratedSave {
            get {
                return ResourceManager.GetString("MigratedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molly.
        /// </summary>
        public static string MollyLabel {
            get {
                return ResourceManager.GetString("MollyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk.
        /// </summary>
        public static string Monk {
            get {
                return ResourceManager.GetString("Monk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi.
        /// </summary>
        public static string Multi {
            get {
                return ResourceManager.GetString("Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muriel.
        /// </summary>
        public static string MurielLabel {
            get {
                return ResourceManager.GetString("MurielLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mythic.
        /// </summary>
        public static string Mythic {
            get {
                return ResourceManager.GetString("Mythic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (A→Z).
        /// </summary>
        public static string NameAtoZ {
            get {
                return ResourceManager.GetString("NameAtoZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Z→A).
        /// </summary>
        public static string NameZtoA {
            get {
                return ResourceManager.GetString("NameZtoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile name....
        /// </summary>
        public static string NewProfileName {
            get {
                return ResourceManager.GetString("NewProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile name....
        /// </summary>
        public static string NewProfilePlaceholder {
            get {
                return ResourceManager.GetString("NewProfilePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightmare.
        /// </summary>
        public static string Nightmare {
            get {
                return ResourceManager.GetString("Nightmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No artifacts found for.
        /// </summary>
        public static string NoArtifactsFound {
            get {
                return ResourceManager.GetString("NoArtifactsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Crew Assigned.
        /// </summary>
        public static string NoCrewAssigned {
            get {
                return ResourceManager.GetString("NoCrewAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No profiles found..
        /// </summary>
        public static string NoProfilesFound {
            get {
                return ResourceManager.GetString("NoProfilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the content you are looking for does not exist..
        /// </summary>
        public static string NotFoundDescription {
            get {
                return ResourceManager.GetString("NotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize for Arena.
        /// </summary>
        public static string OptimizeForArena {
            get {
                return ResourceManager.GetString("OptimizeForArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize for Campaign.
        /// </summary>
        public static string OptimizeForCampaign {
            get {
                return ResourceManager.GetString("OptimizeForCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizer.
        /// </summary>
        public static string Optimizer {
            get {
                return ResourceManager.GetString("Optimizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizing....
        /// </summary>
        public static string Optimizing {
            get {
                return ResourceManager.GetString("Optimizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        public static string Paladin {
            get {
                return ResourceManager.GetString("Paladin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panko.
        /// </summary>
        public static string PankoLabel {
            get {
                return ResourceManager.GetString("PankoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Notes.
        /// </summary>
        public static string PatchNotes {
            get {
                return ResourceManager.GetString("PatchNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See what&apos;s new in the latest version..
        /// </summary>
        public static string PatchNotesDescription {
            get {
                return ResourceManager.GetString("PatchNotesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearl.
        /// </summary>
        public static string Pearl {
            get {
                return ResourceManager.GetString("Pearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum.
        /// </summary>
        public static string Platinum {
            get {
                return ResourceManager.GetString("Platinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priest.
        /// </summary>
        public static string Priest {
            get {
                return ResourceManager.GetString("Priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile created..
        /// </summary>
        public static string ProfileCreated {
            get {
                return ResourceManager.GetString("ProfileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile deleted..
        /// </summary>
        public static string ProfileDeleted {
            get {
                return ResourceManager.GetString("ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile renamed..
        /// </summary>
        public static string ProfileRenamed {
            get {
                return ResourceManager.GetString("ProfileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile switched. Reload to apply..
        /// </summary>
        public static string ProfileSwitched {
            get {
                return ResourceManager.GetString("ProfileSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rage.
        /// </summary>
        public static string Rage {
            get {
                return ResourceManager.GetString("Rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randal.
        /// </summary>
        public static string RandalLabel {
            get {
                return ResourceManager.GetString("RandalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        public static string Ranged {
            get {
                return ResourceManager.GetString("Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        public static string Rarity {
            get {
                return ResourceManager.GetString("Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity (High→Low).
        /// </summary>
        public static string RarityHighToLow {
            get {
                return ResourceManager.GetString("RarityHighToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity (Low→High).
        /// </summary>
        public static string RarityLowToHigh {
            get {
                return ResourceManager.GetString("RarityLowToHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        public static string ResetDefaults {
            get {
                return ResourceManager.GetString("ResetDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your machine and heroes, then click Optimize at the bottom to calculate the best formation..
        /// </summary>
        public static string ResultsEmptyDescription {
            get {
                return ResourceManager.GetString("ResultsEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rickie.
        /// </summary>
        public static string RickieLabel {
            get {
                return ResourceManager.GetString("RickieLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        public static string Rogue {
            get {
                return ResourceManager.GetString("Rogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby.
        /// </summary>
        public static string Ruby {
            get {
                return ResourceManager.GetString("Ruby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacred Card Level.
        /// </summary>
        public static string SacredCardLevel {
            get {
                return ResourceManager.GetString("SacredCardLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sapphire.
        /// </summary>
        public static string Sapphire {
            get {
                return ResourceManager.GetString("Sapphire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data is empty..
        /// </summary>
        public static string SaveDataEmpty {
            get {
                return ResourceManager.GetString("SaveDataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save / Load.
        /// </summary>
        public static string SaveLoad {
            get {
                return ResourceManager.GetString("SaveLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save / Load Configuration.
        /// </summary>
        public static string SaveLoadConfiguration {
            get {
                return ResourceManager.GetString("SaveLoadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Save and copy the JSON generated below to save your config, or paste a saved config and click Load..
        /// </summary>
        public static string SaveLoadConfigurationDescription {
            get {
                return ResourceManager.GetString("SaveLoadConfigurationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save loaded successfully..
        /// </summary>
        public static string SaveLoadedSuccessfully {
            get {
                return ResourceManager.GetString("SaveLoadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a save or paste one here....
        /// </summary>
        public static string SaveLoadPlaceholder {
            get {
                return ResourceManager.GetString("SaveLoadPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarab.
        /// </summary>
        public static string Scarab {
            get {
                return ResourceManager.GetString("Scarab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarab Level.
        /// </summary>
        public static string ScarabLevel {
            get {
                return ResourceManager.GetString("ScarabLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scarab&apos;s Game (Inscription Cards).
        /// </summary>
        public static string ScarabsGameInscriptionCards {
            get {
                return ResourceManager.GetString("ScarabsGameInscriptionCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select rank.
        /// </summary>
        public static string SelectRank {
            get {
                return ResourceManager.GetString("SelectRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a rift rank....
        /// </summary>
        public static string SelectRiftRank {
            get {
                return ResourceManager.GetString("SelectRiftRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sely.
        /// </summary>
        public static string SelyLabel {
            get {
                return ResourceManager.GetString("SelyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel.
        /// </summary>
        public static string SentinelLabel {
            get {
                return ResourceManager.GetString("SentinelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage settings for your active profile..
        /// </summary>
        public static string SettingsDescription {
            get {
                return ResourceManager.GetString("SettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been saved..
        /// </summary>
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaman.
        /// </summary>
        public static string Shaman {
            get {
                return ResourceManager.GetString("Shaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solaine.
        /// </summary>
        public static string SolaineLabel {
            get {
                return ResourceManager.GetString("SolaineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by....
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spellcaster.
        /// </summary>
        public static string Spellcaster {
            get {
                return ResourceManager.GetString("Spellcaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starlight.
        /// </summary>
        public static string Starlight {
            get {
                return ResourceManager.GetString("Starlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starlight Plus.
        /// </summary>
        public static string StarlightPlus {
            get {
                return ResourceManager.GetString("StarlightPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Starlight Plus Wings (Max).
        /// </summary>
        public static string StarlightPlusWingsMachineMaxRank {
            get {
                return ResourceManager.GetString("StarlightPlusWingsMachineMaxRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already at the desired level..
        /// </summary>
        public static string StrangeDustAlreadyAtLevelError {
            get {
                return ResourceManager.GetString("StrangeDustAlreadyAtLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strange Dust Calculator.
        /// </summary>
        public static string StrangeDustCalculator {
            get {
                return ResourceManager.GetString("StrangeDustCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate Strange Dust needed to level up your Guardian..
        /// </summary>
        public static string StrangeDustCalculatorDescription {
            get {
                return ResourceManager.GetString("StrangeDustCalculatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot go from a Crown rank back to a Star rank..
        /// </summary>
        public static string StrangeDustCrownToStarError {
            get {
                return ResourceManager.GetString("StrangeDustCrownToStarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target must be higher than current position..
        /// </summary>
        public static string StrangeDustCurrentHigherThanTargetError {
            get {
                return ResourceManager.GetString("StrangeDustCurrentHigherThanTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current level must be between 1 and 10..
        /// </summary>
        public static string StrangeDustCurrentLevelError {
            get {
                return ResourceManager.GetString("StrangeDustCurrentLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target level must be higher than current level at the same rank..
        /// </summary>
        public static string StrangeDustCurrentLevelHigherThanTargetSameRank {
            get {
                return ResourceManager.GetString("StrangeDustCurrentLevelHigherThanTargetSameRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level must be between 1 and 10..
        /// </summary>
        public static string StrangeDustErrorLevel {
            get {
                return ResourceManager.GetString("StrangeDustErrorLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXP cannot be negative..
        /// </summary>
        public static string StrangeDustErrorNegativeEXP {
            get {
                return ResourceManager.GetString("StrangeDustErrorNegativeEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target level must be between 1 and 10..
        /// </summary>
        public static string StrangeDustTargetLevelError {
            get {
                return ResourceManager.GetString("StrangeDustTargetLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talia.
        /// </summary>
        public static string TaliaLabel {
            get {
                return ResourceManager.GetString("TaliaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talos.
        /// </summary>
        public static string TalosLabel {
            get {
                return ResourceManager.GetString("TalosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        public static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Position.
        /// </summary>
        public static string TargetPosition {
            get {
                return ResourceManager.GetString("TargetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Type.
        /// </summary>
        public static string TargetType {
            get {
                return ResourceManager.GetString("TargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavern.
        /// </summary>
        public static string Tavern {
            get {
                return ResourceManager.GetString("Tavern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavern (Sacred Cards).
        /// </summary>
        public static string TavernSacredCards {
            get {
                return ResourceManager.GetString("TavernSacredCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderclap.
        /// </summary>
        public static string ThunderclapLabel {
            get {
                return ResourceManager.GetString("ThunderclapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titan.
        /// </summary>
        public static string Titan {
            get {
                return ResourceManager.GetString("Titan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Squad.
        /// </summary>
        public static string TotalSquad {
            get {
                return ResourceManager.GetString("TotalSquad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Stars.
        /// </summary>
        public static string TotalStars {
            get {
                return ResourceManager.GetString("TotalStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Strange Dust Needed.
        /// </summary>
        public static string TotalStrangeDustNeeded {
            get {
                return ResourceManager.GetString("TotalStrangeDustNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        public static string Uncommon {
            get {
                return ResourceManager.GetString("Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfigured First.
        /// </summary>
        public static string UnconfiguredFirst {
            get {
                return ResourceManager.GetString("UnconfiguredFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown save version.
        /// </summary>
        public static string UnknownSaveVersion {
            get {
                return ResourceManager.GetString("UnknownSaveVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valerius.
        /// </summary>
        public static string ValeriusLabel {
            get {
                return ResourceManager.GetString("ValeriusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilon.
        /// </summary>
        public static string VilonLabel {
            get {
                return ResourceManager.GetString("VilonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock.
        /// </summary>
        public static string Warlock {
            get {
                return ResourceManager.GetString("Warlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        public static string Warrior {
            get {
                return ResourceManager.GetString("Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yamanoth.
        /// </summary>
        public static string YamanothLabel {
            get {
                return ResourceManager.GetString("YamanothLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yavo.
        /// </summary>
        public static string YavoLabel {
            get {
                return ResourceManager.GetString("YavoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zelea.
        /// </summary>
        public static string ZeleaLabel {
            get {
                return ResourceManager.GetString("ZeleaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoruk.
        /// </summary>
        public static string ZorukLabel {
            get {
                return ResourceManager.GetString("ZorukLabel", resourceCulture);
            }
        }
    }
}
