name: Deploy Subfolder to Branch

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Subfolder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./InfatalsFirestoneTools/bin/Release/net10.0/browser-wasm/publish/wwwroot  # The folder you want to move
          publish_branch: gh-pages 
